apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-first-topic
  labels:
    strimzi.io/cluster: strimzi-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824