apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-first-topic
  labels:
    strimzi.io/cluster: strimzi-cluster
spec:
  partitions: 2
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: just-a-test
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 600000 # setting very low retention of 10min
