apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-kafka-streams
  name: java-kafka-streams
  namespace: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-streams
  template:
    metadata:
      labels:
        app: java-kafka-streams
    spec:
      containers:
        - name: java-kafka-streams
          image: quay.io/strimzi-examples/java-kafka-streams:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: strimzi-cluster-kafka-bootstrap.kafka-cluster:9092
            - name: APPLICATION_ID
              value: java-kafka-streams
            - name: SOURCE_TOPIC
              value: my-topic
            - name: TARGET_TOPIC
              value: my-topic-reversed
            - name: LOG_LEVEL
              value: "INFO"
            - name: JAEGER_SERVICE_NAME
              value: java-kafka-streams
            - name: JAEGER_AGENT_HOST
              value: my-jaeger-agent
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"