apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-kafka-consumer
  name: java-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-consumer
  template:
    metadata:
      labels:
        app: java-kafka-consumer
    spec:
      containers:
        - name: java-kafka-consumer
          image: quay.io/strimzi-examples/java-kafka-consumer:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: strimzi-cluster-kafka-bootstrap.kafka-cluster:9092
            - name: TOPIC
              value: my-topic-reversed
            - name: GROUP_ID
              value: java-kafka-consumer
            - name: LOG_LEVEL
              value: "INFO"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: JAEGER_SERVICE_NAME
              value: java-kafka-consumer
            - name: JAEGER_AGENT_HOST
              value: my-jaeger-agent
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"