apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base/
namespace: kafka-cluster
namePrefix: prod-
patchesStrategicMerge:
- kafka-config-patch.yaml
- zookeeper-config-patch.yaml